/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef AtsType_CONSTANTS_H
#define AtsType_CONSTANTS_H

#include "AtsType_types.h"

namespace AtsType {

class AtsTypeConstants {
 public:
  AtsTypeConstants();

};

extern const AtsTypeConstants g_AtsType_constants;

} // namespace

#endif
