/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AtsType_constants.h"

namespace AtsType {

const AtsTypeConstants g_AtsType_constants;

AtsTypeConstants::AtsTypeConstants() {
}

} // namespace

