/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AtsGeneral_constants.h"

namespace AtsGeneral {

const AtsGeneralConstants g_AtsGeneral_constants;

AtsGeneralConstants::AtsGeneralConstants() {
}

} // namespace

