/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SimpleAtsOperation.h"

namespace SimpleMsg {


SimpleAtsOperation_CreateAutomaton_args::~SimpleAtsOperation_CreateAutomaton_args() throw() {
}


uint32_t SimpleAtsOperation_CreateAutomaton_args::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->automatonName);
          this->__isset.automatonName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->underlyingName);
          this->__isset.underlyingName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->feedsourcesStr);
          this->__isset.feedsourcesStr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->connectionsStr);
          this->__isset.connectionsStr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->stocks);
          this->__isset.stocks = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SimpleAtsOperation_CreateAutomaton_args::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SimpleAtsOperation_CreateAutomaton_args");

  xfer += oprot->writeFieldBegin("automatonName", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->automatonName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("underlyingName", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->underlyingName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("feedsourcesStr", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->feedsourcesStr);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("connectionsStr", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->connectionsStr);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("stocks", ::apache::thrift::protocol::T_STRING, 5);
  xfer += oprot->writeString(this->stocks);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}


SimpleAtsOperation_CreateAutomaton_pargs::~SimpleAtsOperation_CreateAutomaton_pargs() throw() {
}


uint32_t SimpleAtsOperation_CreateAutomaton_pargs::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SimpleAtsOperation_CreateAutomaton_pargs");

  xfer += oprot->writeFieldBegin("automatonName", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString((*(this->automatonName)));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("underlyingName", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString((*(this->underlyingName)));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("feedsourcesStr", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString((*(this->feedsourcesStr)));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("connectionsStr", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString((*(this->connectionsStr)));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("stocks", ::apache::thrift::protocol::T_STRING, 5);
  xfer += oprot->writeString((*(this->stocks)));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}


SimpleAtsOperation_CreateAutomaton_result::~SimpleAtsOperation_CreateAutomaton_result() throw() {
}


uint32_t SimpleAtsOperation_CreateAutomaton_result::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->success.read(iprot);
          this->__isset.success = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SimpleAtsOperation_CreateAutomaton_result::write(::apache::thrift::protocol::TProtocol* oprot) const {

  uint32_t xfer = 0;

  xfer += oprot->writeStructBegin("SimpleAtsOperation_CreateAutomaton_result");

  if (this->__isset.success) {
    xfer += oprot->writeFieldBegin("success", ::apache::thrift::protocol::T_STRUCT, 0);
    xfer += this->success.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}


SimpleAtsOperation_CreateAutomaton_presult::~SimpleAtsOperation_CreateAutomaton_presult() throw() {
}


uint32_t SimpleAtsOperation_CreateAutomaton_presult::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += (*(this->success)).read(iprot);
          this->__isset.success = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

void SimpleAtsOperationClient::CreateAutomaton(SimpleAtsMsg& _return, const std::string& automatonName, const std::string& underlyingName, const std::string& feedsourcesStr, const std::string& connectionsStr, const std::string& stocks)
{
  send_CreateAutomaton(automatonName, underlyingName, feedsourcesStr, connectionsStr, stocks);
  recv_CreateAutomaton(_return);
}

void SimpleAtsOperationClient::send_CreateAutomaton(const std::string& automatonName, const std::string& underlyingName, const std::string& feedsourcesStr, const std::string& connectionsStr, const std::string& stocks)
{
  int32_t cseqid = 0;
  oprot_->writeMessageBegin("CreateAutomaton", ::apache::thrift::protocol::T_CALL, cseqid);

  SimpleAtsOperation_CreateAutomaton_pargs args;
  args.automatonName = &automatonName;
  args.underlyingName = &underlyingName;
  args.feedsourcesStr = &feedsourcesStr;
  args.connectionsStr = &connectionsStr;
  args.stocks = &stocks;
  args.write(oprot_);

  oprot_->writeMessageEnd();
  oprot_->getTransport()->writeEnd();
  oprot_->getTransport()->flush();
}

void SimpleAtsOperationClient::recv_CreateAutomaton(SimpleAtsMsg& _return)
{

  int32_t rseqid = 0;
  std::string fname;
  ::apache::thrift::protocol::TMessageType mtype;

  iprot_->readMessageBegin(fname, mtype, rseqid);
  if (mtype == ::apache::thrift::protocol::T_EXCEPTION) {
    ::apache::thrift::TApplicationException x;
    x.read(iprot_);
    iprot_->readMessageEnd();
    iprot_->getTransport()->readEnd();
    throw x;
  }
  if (mtype != ::apache::thrift::protocol::T_REPLY) {
    iprot_->skip(::apache::thrift::protocol::T_STRUCT);
    iprot_->readMessageEnd();
    iprot_->getTransport()->readEnd();
  }
  if (fname.compare("CreateAutomaton") != 0) {
    iprot_->skip(::apache::thrift::protocol::T_STRUCT);
    iprot_->readMessageEnd();
    iprot_->getTransport()->readEnd();
  }
  SimpleAtsOperation_CreateAutomaton_presult result;
  result.success = &_return;
  result.read(iprot_);
  iprot_->readMessageEnd();
  iprot_->getTransport()->readEnd();

  if (result.__isset.success) {
    // _return pointer has now been filled
    return;
  }
  throw ::apache::thrift::TApplicationException(::apache::thrift::TApplicationException::MISSING_RESULT, "CreateAutomaton failed: unknown result");
}

bool SimpleAtsOperationProcessor::dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) {
  ProcessMap::iterator pfn;
  pfn = processMap_.find(fname);
  if (pfn == processMap_.end()) {
    return  ::AtsGeneral::AtsOperationProcessor::dispatchCall(iprot, oprot, fname, seqid, callContext);
  }
  (this->*(pfn->second))(seqid, iprot, oprot, callContext);
  return true;
}

void SimpleAtsOperationProcessor::process_CreateAutomaton(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext)
{
  void* ctx = NULL;
  if (this->eventHandler_.get() != NULL) {
    ctx = this->eventHandler_->getContext("SimpleAtsOperation.CreateAutomaton", callContext);
  }
  ::apache::thrift::TProcessorContextFreer freer(this->eventHandler_.get(), ctx, "SimpleAtsOperation.CreateAutomaton");

  if (this->eventHandler_.get() != NULL) {
    this->eventHandler_->preRead(ctx, "SimpleAtsOperation.CreateAutomaton");
  }

  SimpleAtsOperation_CreateAutomaton_args args;
  args.read(iprot);
  iprot->readMessageEnd();
  uint32_t bytes = iprot->getTransport()->readEnd();

  if (this->eventHandler_.get() != NULL) {
    this->eventHandler_->postRead(ctx, "SimpleAtsOperation.CreateAutomaton", bytes);
  }

  SimpleAtsOperation_CreateAutomaton_result result;
  try {
    iface_->CreateAutomaton(result.success, args.automatonName, args.underlyingName, args.feedsourcesStr, args.connectionsStr, args.stocks);
    result.__isset.success = true;
  } catch (const std::exception& e) {
    if (this->eventHandler_.get() != NULL) {
      this->eventHandler_->handlerError(ctx, "SimpleAtsOperation.CreateAutomaton");
    }

    ::apache::thrift::TApplicationException x(e.what());
    oprot->writeMessageBegin("CreateAutomaton", ::apache::thrift::protocol::T_EXCEPTION, seqid);
    x.write(oprot);
    oprot->writeMessageEnd();
    oprot->getTransport()->writeEnd();
    oprot->getTransport()->flush();
    return;
  }

  if (this->eventHandler_.get() != NULL) {
    this->eventHandler_->preWrite(ctx, "SimpleAtsOperation.CreateAutomaton");
  }

  oprot->writeMessageBegin("CreateAutomaton", ::apache::thrift::protocol::T_REPLY, seqid);
  result.write(oprot);
  oprot->writeMessageEnd();
  bytes = oprot->getTransport()->writeEnd();
  oprot->getTransport()->flush();

  if (this->eventHandler_.get() != NULL) {
    this->eventHandler_->postWrite(ctx, "SimpleAtsOperation.CreateAutomaton", bytes);
  }
}

::boost::shared_ptr< ::apache::thrift::TProcessor > SimpleAtsOperationProcessorFactory::getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) {
  ::apache::thrift::ReleaseHandler< SimpleAtsOperationIfFactory > cleanup(handlerFactory_);
  ::boost::shared_ptr< SimpleAtsOperationIf > handler(handlerFactory_->getHandler(connInfo), cleanup);
  ::boost::shared_ptr< ::apache::thrift::TProcessor > processor(new SimpleAtsOperationProcessor(handler));
  return processor;
}

void SimpleAtsOperationConcurrentClient::CreateAutomaton(SimpleAtsMsg& _return, const std::string& automatonName, const std::string& underlyingName, const std::string& feedsourcesStr, const std::string& connectionsStr, const std::string& stocks)
{
  int32_t seqid = send_CreateAutomaton(automatonName, underlyingName, feedsourcesStr, connectionsStr, stocks);
  recv_CreateAutomaton(_return, seqid);
}

int32_t SimpleAtsOperationConcurrentClient::send_CreateAutomaton(const std::string& automatonName, const std::string& underlyingName, const std::string& feedsourcesStr, const std::string& connectionsStr, const std::string& stocks)
{
  int32_t cseqid = this->sync_.generateSeqId();
  ::apache::thrift::async::TConcurrentSendSentry sentry(&this->sync_);
  oprot_->writeMessageBegin("CreateAutomaton", ::apache::thrift::protocol::T_CALL, cseqid);

  SimpleAtsOperation_CreateAutomaton_pargs args;
  args.automatonName = &automatonName;
  args.underlyingName = &underlyingName;
  args.feedsourcesStr = &feedsourcesStr;
  args.connectionsStr = &connectionsStr;
  args.stocks = &stocks;
  args.write(oprot_);

  oprot_->writeMessageEnd();
  oprot_->getTransport()->writeEnd();
  oprot_->getTransport()->flush();

  sentry.commit();
  return cseqid;
}

void SimpleAtsOperationConcurrentClient::recv_CreateAutomaton(SimpleAtsMsg& _return, const int32_t seqid)
{

  int32_t rseqid = 0;
  std::string fname;
  ::apache::thrift::protocol::TMessageType mtype;

  // the read mutex gets dropped and reacquired as part of waitForWork()
  // The destructor of this sentry wakes up other clients
  ::apache::thrift::async::TConcurrentRecvSentry sentry(&this->sync_, seqid);

  while(true) {
    if(!this->sync_.getPending(fname, mtype, rseqid)) {
      iprot_->readMessageBegin(fname, mtype, rseqid);
    }
    if(seqid == rseqid) {
      if (mtype == ::apache::thrift::protocol::T_EXCEPTION) {
        ::apache::thrift::TApplicationException x;
        x.read(iprot_);
        iprot_->readMessageEnd();
        iprot_->getTransport()->readEnd();
        sentry.commit();
        throw x;
      }
      if (mtype != ::apache::thrift::protocol::T_REPLY) {
        iprot_->skip(::apache::thrift::protocol::T_STRUCT);
        iprot_->readMessageEnd();
        iprot_->getTransport()->readEnd();
      }
      if (fname.compare("CreateAutomaton") != 0) {
        iprot_->skip(::apache::thrift::protocol::T_STRUCT);
        iprot_->readMessageEnd();
        iprot_->getTransport()->readEnd();

        // in a bad state, don't commit
        using ::apache::thrift::protocol::TProtocolException;
        throw TProtocolException(TProtocolException::INVALID_DATA);
      }
      SimpleAtsOperation_CreateAutomaton_presult result;
      result.success = &_return;
      result.read(iprot_);
      iprot_->readMessageEnd();
      iprot_->getTransport()->readEnd();

      if (result.__isset.success) {
        // _return pointer has now been filled
        sentry.commit();
        return;
      }
      // in a bad state, don't commit
      throw ::apache::thrift::TApplicationException(::apache::thrift::TApplicationException::MISSING_RESULT, "CreateAutomaton failed: unknown result");
    }
    // seqid != rseqid
    this->sync_.updatePending(fname, mtype, rseqid);

    // this will temporarily unlock the readMutex, and let other clients get work done
    this->sync_.waitForWork(seqid);
  } // end while(true)
}

} // namespace

