/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SimpleAtsMsg_constants.h"

namespace SimpleMsg {

const SimpleAtsMsgConstants g_SimpleAtsMsg_constants;

SimpleAtsMsgConstants::SimpleAtsMsgConstants() {
}

} // namespace

