/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SimpleAtsMsg_CONSTANTS_H
#define SimpleAtsMsg_CONSTANTS_H

#include "SimpleAtsMsg_types.h"

namespace SimpleMsg {

class SimpleAtsMsgConstants {
 public:
  SimpleAtsMsgConstants();

};

extern const SimpleAtsMsgConstants g_SimpleAtsMsg_constants;

} // namespace

#endif
