/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef AtsGeneral_CONSTANTS_H
#define AtsGeneral_CONSTANTS_H

#include "AtsGeneral_types.h"

namespace AtsGeneral {

class AtsGeneralConstants {
 public:
  AtsGeneralConstants();

};

extern const AtsGeneralConstants g_AtsGeneral_constants;

} // namespace

#endif
